Repository AkitaInteractive/Hachiko-Engine, pull requests merged in 2022-06, with the labels that each got.

#165 Fixed weird bug occuring on coexisting image and text components.
  Source/src/components/ComponentImage.cpp
  Source/src/components/ComponentText.cpp
  Source/src/components/ComponentText.h
  Source/src/core/GameObject.cpp
  Source/src/modules/ModuleUserInterface.cpp
  Source/src/modules/ModuleUserInterface.h
  Source/vendors/GLFont/FTLabel.cpp
Labels: enhancement, bugfix

#179 Renaming render variable
  Source/src/modules/ModuleRender.cpp
  Source/src/modules/ModuleRender.h
Labels: improvement

#187 Fixing build race condition
  Gameplay/Gameplay.vcxproj
  Source/Engine.vcxproj
Labels: bugfix

#186 Fix error when removing components
  Source/.clang-format
  Source/src/core/GameObject.cpp
  Source/src/core/GameObject.h
  Source/src/modules/ModuleEditor.cpp
  Source/src/modules/ModuleEditor.h
  Source/src/modules/ModuleSceneManager.cpp
  Source/src/ui/ImguiUtils.cpp
Labels: bugfix

#201 Fixed&Added Menus, Fixed button click issue on Engine play mode, and last open scene autosave is now disabled on PLAY_BUILD
  Game/assets/scenes/Menu.scene
  Game/assets/scenes/Menu.scene.meta
  Source/src/modules/ModuleSceneManager.cpp
  Source/src/modules/ModuleUserInterface.cpp
Labels: enhancement, bugfix

#208 Rounding floats in serialization
  Source/src/core/serialization/TypeConverter.h
Labels: enhancement
