Repository AkitaInteractive/Hachiko-Engine, pull requests merged in 2022-09, with the labels that each got.

#309 Fixed Level 2 crystals without CrystalExplosion script attached throwing error issue.
  Gameplay/entities/player/CombatManager.cpp
Labels: bugfix

#313 Async loading of scenes, which does not block the main thread and shows loading screen instead.
  Game/assets/textures/Loading.png
  Game/assets/textures/Loading.png.meta
  Gameplay/Gameplay.vcxproj
  Gameplay/entities/player/PlayerController.cpp
  Gameplay/misc/LaserController.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/src/Application.cpp
  Source/src/Application.h
  Source/src/Batching/TextureBatch.cpp
  Source/src/Gameplay.cpp
  Source/src/Gameplay.h
  Source/src/Main.cpp
  Source/src/components/ComponentAnimation.cpp
  Source/src/components/ComponentAnimation.h
  Source/src/components/ComponentBillboard.cpp
  Source/src/components/ComponentBillboard.h
  Source/src/components/ComponentImage.cpp
  Source/src/components/ComponentImage.h
  Source/src/components/ComponentMeshRenderer.cpp
  Source/src/components/ComponentMeshRenderer.h
  Source/src/components/ComponentObstacle.h
  Source/src/components/ComponentParticleSystem.cpp
  Source/src/components/ComponentParticleSystem.h
  Source/src/components/ComponentText.cpp
  Source/src/components/ComponentText.h
  Source/src/core/GameObject.cpp
  Source/src/core/GameObject.h
  Source/src/core/Scene.cpp
  Source/src/core/Scene.h
  Source/src/core/preferences/src/EditorPreferences.cpp
  Source/src/core/preferences/src/EditorPreferences.h
  Source/src/core/rendering/Skybox.cpp
  Source/src/core/rendering/Skybox.h
  Source/src/core/serialization/Definitions.h
  Source/src/importers/MeshImporter.cpp
  Source/src/importers/TextureImporter.cpp
  Source/src/modules/ModuleAudio.cpp
  Source/src/modules/ModuleAudio.h
  Source/src/modules/ModuleCamera.h
  Source/src/modules/ModuleDebugDraw.h
  Source/src/modules/ModuleDebugMode.cpp
  Source/src/modules/ModuleDebugMode.h
  Source/src/modules/ModuleEditor.h
  Source/src/modules/ModuleInput.h
  Source/src/modules/ModuleRender.cpp
  Source/src/modules/ModuleRender.h
  Source/src/modules/ModuleResources.cpp
  Source/src/modules/ModuleResources.h
  Source/src/modules/ModuleSceneManager.cpp
  Source/src/modules/ModuleSceneManager.h
  Source/src/modules/ModuleScriptingSystem.cpp
  Source/src/modules/ModuleUserInterface.cpp
  Source/src/resources/ResourceMesh.cpp
  Source/src/resources/ResourceMesh.h
  Source/src/ui/WindowConfiguration.cpp
  Source/src/ui/WindowScene.cpp
  Source/src/utils/ComponentUtility.h
Labels: enhancement, improvement

#332 Implemented time scaling api and logic for slow motion capabilities.
  Gameplay/scriptingUtil/gameplaypch.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/src/Gameplay.cpp
  Source/src/Gameplay.h
  Source/src/components/Component.h
  Source/src/components/ComponentAgent.cpp
  Source/src/components/ComponentAgent.h
  Source/src/components/ComponentAnimation.cpp
  Source/src/components/ComponentAnimation.h
  Source/src/components/ComponentBillboard.cpp
  Source/src/components/ComponentBillboard.h
  Source/src/components/ComponentParticleSystem.cpp
  Source/src/components/ComponentParticleSystem.h
  Source/src/components/TimeScaleMode.h
  Source/src/components/animation/AnimationController.cpp
  Source/src/components/animation/AnimationController.h
  Source/src/core/GameObject.cpp
  Source/src/core/GameObject.h
  Source/src/core/particles/Particle.cpp
  Source/src/core/particles/Particle.h
  Source/src/core/particles/ParticleModifier.h
  Source/src/core/particles/modifiers/AnimationParticleModifier.cpp
  Source/src/core/particles/modifiers/AnimationParticleModifier.h
  Source/src/core/particles/modifiers/ColorParticleModifier.cpp
  Source/src/core/particles/modifiers/ColorParticleModifier.h
  Source/src/core/particles/modifiers/ForceParticleModifier.cpp
  Source/src/core/particles/modifiers/ForceParticleModifier.h
  Source/src/core/particles/modifiers/NoiseParticleModifier.cpp
  Source/src/core/particles/modifiers/NoiseParticleModifier.h
  Source/src/core/particles/modifiers/SizeParticleModifier.cpp
  Source/src/core/particles/modifiers/SizeParticleModifier.h
  Source/src/core/particles/modifiers/VelocityParticleModifier.cpp
  Source/src/core/particles/modifiers/VelocityParticleModifier.h
  Source/src/events/Event.h
  Source/src/events/TimeScaleChangeEventPayload.h
  Source/src/ui/WindowScene.cpp
Labels: enhancement

#362 Added boss jump logic and skeleton.
  Game/assets/prefabs/StalagmiteManager.prefab
  Game/assets/prefabs/StalagmiteManager.prefab.meta
  Game/assets/scenes/Boss.scene
  Game/assets/scenes/Boss.scene.meta
  Gameplay/Gameplay.vcxproj
  Gameplay/entities/enemies/BossController.cpp
  Gameplay/entities/enemies/BossController.h
  Gameplay/misc/StalagmiteManager.cpp
  Gameplay/misc/StalagmiteManager.h
  Source/Engine.vcxproj
  Source/build_scripts.bat
  Source/src/modules/ModuleEditor.cpp
Labels: enhancement, improvement
