Repository AkitaInteractive/Hachiko-Engine, pull requests merged in 2022-08, with the labels that each got.

#282 Fix worm invisible && attacking right at spawn
  Game/assets/state_machine/wormDistanceSM.stm
  Game/assets/state_machine/wormDistanceSM.stm.meta
  Gameplay/entities/enemies/EnemyController.cpp
Labels: bugfix

#277 Implemented bloom effect, did refactorings on module render and gaussian blur shader.
  Game/assets/materials/PLayer_base.mat.meta
  Game/assets/materials/crystalSpike_material1.mat
  Game/assets/materials/crystalSpike_material1.mat.meta
  Game/assets/textures/crystal/CrystalSpike_txt/crystalSpike_mesh_e.png
  Game/assets/textures/crystal/CrystalSpike_txt/crystalSpike_mesh_e.png.meta
  Game/shaders/common/uniforms/lights_uniform.glsl
  Game/shaders/fragment_deferred_lighting.glsl
  Game/shaders/fragment_gaussian_filter.glsl
  Game/shaders/fragment_texture_copy.glsl
  Game/shaders/vertex_texture_copy.glsl
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/src/Application.cpp
  Source/src/Batching/BatchManager.cpp
  Source/src/Batching/TextureBatch.cpp
  Source/src/components/ComponentBillboard.cpp
  Source/src/components/ComponentVideo.cpp
  Source/src/core/particles/Particle.cpp
  Source/src/core/preferences/PreferenceManager.cpp
  Source/src/core/preferences/PreferenceManager.h
  Source/src/core/preferences/src/EditorPreferences.cpp
  Source/src/core/rendering/BloomManager.cpp
  Source/src/core/rendering/BloomManager.h
  Source/src/core/rendering/BlurPixelSize.cpp
  Source/src/core/rendering/BlurPixelSize.h
  Source/src/core/rendering/GBuffer.cpp
  Source/src/core/rendering/GBuffer.h
  Source/src/core/rendering/ShadowManager.cpp
  Source/src/core/rendering/ShadowMappingProperties.cpp
  Source/src/core/rendering/ShadowMappingProperties.h
  Source/src/core/rendering/Skybox.cpp
  Source/src/core/rendering/StandaloneGLTexture.cpp
  Source/src/core/rendering/StandaloneGLTexture.h
  Source/src/core/rendering/Uniforms.h
  Source/src/modules/ModuleProgram.cpp
  Source/src/modules/ModuleProgram.h
  Source/src/modules/ModuleRender.cpp
  Source/src/modules/ModuleRender.h
Labels: enhancement

#292 Implemented mouse input ignoring outside scene window on engine mode while scene is playing; Added play mode indicator.
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/src/Gameplay.cpp
  Source/src/Gameplay.h
  Source/src/core/hepch.h
  Source/src/modules/ModuleInput.cpp
  Source/src/modules/ModuleInput.h
  Source/src/ui/WindowScene.cpp
  Source/src/ui/WindowScene.h
  Source/src/utils/MathUtil.h
  Source/vendors/imgui/imgui.h
  Source/vendors/imgui/imgui_widgets.cpp
Labels: enhancement, improvement

#296 Added application quitting api to Application and Gameplay; Implemented the functioning quit button on menu scene.
  Gameplay/ui/MainMenuManager.cpp
  Gameplay/ui/MainMenuManager.h
  Source/src/Application.cpp
  Source/src/Application.h
  Source/src/Gameplay.cpp
  Source/src/Gameplay.h
  Source/src/modules/ModuleEditor.cpp
  Source/src/modules/ModuleEditor.h
Labels: enhancement, improvement

#300 Fixed game not playing on PLAY_BUILD; Refactored ModuleSceneManager to own GameTimer fully, and added option to force start the loaded scene.
  Source/src/Application.cpp
  Source/src/components/ComponentParticleSystem.cpp
  Source/src/components/animation/AnimationController.cpp
  Source/src/core/Scene.cpp
  Source/src/modules/ModuleSceneManager.cpp
  Source/src/modules/ModuleSceneManager.h
  Source/vendors/MathGeoLib/MathBuildConfig.h
Labels: bugfix, improvement

#304 Fixed mouse position for UI components not working issue on PLAY_BUILD. Added OpenGL Mouse position API. Refactored UI button click & hover logic.
  Source/src/Gameplay.cpp
  Source/src/Gameplay.h
  Source/src/components/ComponentParticleSystem.cpp
  Source/src/events/MouseEventPayload.h
  Source/src/modules/ModuleInput.cpp
  Source/src/modules/ModuleInput.h
  Source/src/modules/ModuleUserInterface.cpp
  Source/src/modules/ModuleUserInterface.h
  Source/src/modules/ModuleWindow.h
  Source/src/ui/WindowScene.cpp
  Source/src/ui/WindowScene.h
Labels: bugfix, improvement

#307 Fixed particle and billboard sizes on level 2.
  Game/assets/scenes/Level2.scene
  Game/assets/scenes/Level2.scene.meta
  Source/src/core/rendering/RenderList.cpp
Labels: bugfix, improvement
