Repository AkitaInteractive/Hachiko-Engine, pull requests merged in 2022-10, with the labels that each got.

#373 Add effect scripts
  Game/assets/scenes/TestScene.scene
  Game/assets/scenes/TestScene.scene.meta
  Gameplay/Gameplay.vcxproj
  Gameplay/Gameplay.vcxproj.filters
  Gameplay/effects/BounceEffect.cpp
  Gameplay/effects/BounceEffect.h
  Gameplay/effects/HoverEffect.cpp
  Gameplay/effects/HoverEffect.h
  Gameplay/effects/RotationEffect.cpp
  Gameplay/effects/RotationEffect.h
Labels: enhancement

#387 Fixing the issue that make effects in scenes unable to load
  Gameplay/effects/BounceEffect.cpp
  Gameplay/effects/HoverEffect.cpp
  Gameplay/effects/RotationEffect.cpp
Labels: bugfix

#404 Fix: Translucid meshes are drawn after fog
  Game/shaders/fragment_deferred_transparent_depth.glsl
  Source/src/core/rendering/Program.h
  Source/src/modules/ModuleProgram.cpp
  Source/src/modules/ModuleRender.cpp
Labels: bugfix

#425 Implemented SSAO and "Recompile Shaders" Button on Editor.
  Game/shaders/fragment_deferred_lighting.glsl
  Game/shaders/fragment_ssao.glsl
  Game/shaders/vertex_ssao.glsl
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/src/Batching/GeometryBatch.h
  Source/src/components/ComponentVideo.cpp
  Source/src/core/Scene.cpp
  Source/src/core/preferences/src/EditorPreferences.cpp
  Source/src/core/preferences/src/EditorPreferences.h
  Source/src/core/rendering/BloomManager.cpp
  Source/src/core/rendering/BloomManager.h
  Source/src/core/rendering/BlurConfig.cpp
  Source/src/core/rendering/BlurConfig.h
  Source/src/core/rendering/BlurPixelSize.cpp
  Source/src/core/rendering/BlurPixelSize.h
  Source/src/core/rendering/GBuffer.cpp
  Source/src/core/rendering/GBuffer.h
  Source/src/core/rendering/Program.h
  Source/src/core/rendering/SSAOManager.cpp
  Source/src/core/rendering/SSAOManager.h
  Source/src/core/rendering/ShadowMappingProperties.cpp
  Source/src/core/rendering/ShadowMappingProperties.h
  Source/src/core/rendering/Skybox.cpp
  Source/src/core/rendering/StandaloneGLTexture.cpp
  Source/src/core/rendering/StandaloneGLTexture.h
  Source/src/core/rendering/Uniforms.h
  Source/src/core/serialization/Definitions.h
  Source/src/modules/ModuleEditor.cpp
  Source/src/modules/ModuleProgram.cpp
  Source/src/modules/ModuleProgram.h
  Source/src/modules/ModuleRender.cpp
  Source/src/modules/ModuleRender.h
  Source/src/modules/ModuleUserInterface.cpp
  Source/src/resources/ResourceMaterial.cpp
  Source/src/resources/ResourceMaterial.h
Labels: enhancement, improvement

#438 Fixed white band issue on SSAO texture.
  Game/shaders/fragment_ssao.glsl
Labels: bugfix, improvement

#450 Hotfix: Ranged attack crashing game on non boss levels.
  Gameplay/entities/player/CombatManager.cpp
Labels: bugfix, improvement

#452 Applied Carlos's suggestions on SSAO.
  Game/shaders/fragment_deferred_lighting.glsl
  Game/shaders/fragment_ssao.glsl
  Source/src/core/rendering/BlurConfig.h
  Source/src/core/rendering/SSAOManager.cpp
  Source/src/core/rendering/SSAOManager.h
  Source/src/core/rendering/Uniforms.h
  Source/src/modules/ModuleRender.cpp
Labels: enhancement, improvement

#456 Stalactites Update
  Game/assets/prefabs/Stalagmite.prefab
  Game/assets/scenes/Boss.scene
  Gameplay/entities/crystals/CrystalExplosion.cpp
  Gameplay/entities/crystals/Stalagmite.cpp
  Gameplay/entities/crystals/Stalagmite.h
  Gameplay/entities/enemies/BossController.cpp
  Gameplay/entities/enemies/EnemyController.cpp
  Gameplay/entities/enemies/EnemyController.h
  Gameplay/entities/player/CombatVisualEffectsPool.cpp
  Gameplay/entities/player/PlayerController.cpp
  Gameplay/misc/StalagmiteManager.cpp
  Gameplay/misc/StalagmiteManager.h
Labels: block boss level
