Repository AkitaInteractive/Hachiko-Engine, pull requests merged in 2022-11, with the labels that each got.

#462 Anti Aliasing with FXAA
  Game/shaders/fragment_fxaa_filter.glsl
  Game/shaders/vertex_fxaa_filter.glsl
  Gameplay/entities/crystals/CrystalExplosion.cpp
  Source/src/core/rendering/Program.h
  Source/src/core/rendering/Uniforms.h
  Source/src/modules/ModuleProgram.cpp
  Source/src/modules/ModuleRender.cpp
  Source/src/modules/ModuleRender.h
Labels: enhancement

#467 Fix stalactites bugs
  Game/assets/scenes/Boss.scene
  Game/assets/scenes/Boss.scene.meta
  Gameplay/entities/crystals/CrystalExplosion.cpp
  Gameplay/entities/crystals/CrystalExplosion.h
  Gameplay/entities/crystals/Stalagmite.cpp
  Gameplay/entities/crystals/Stalagmite.h
  Gameplay/entities/enemies/BossController.cpp
  Gameplay/entities/enemies/BossController.h
  Gameplay/misc/LaserController.cpp
  Gameplay/misc/StalagmiteManager.cpp
  Gameplay/misc/StalagmiteManager.h
Labels: bugfix, block boss level

#469 Boss crystals are hittable
  Game/assets/scenes/Boss.scene
  Game/assets/scenes/Boss.scene.meta
Labels: block boss level

#483 Restyled dark theme UI.
  Source/src/modules/ModuleEditor.cpp
  Source/src/modules/ModuleWindow.cpp
  Source/src/ui/editor/Theme.h
Labels: enhancement

#490 Update README.md
  README.md
Labels: documentation

#501 Fixed ambient color.
  Game/shaders/fragment_deferred_lighting.glsl
Labels: enhancement
