Repository AkitaInteractive/Hachiko-Engine, pull requests merged in 2022-03, with the labels that each got.

#15 Added ComponentTransform logic of Strawhat Engine.
  Source/src/components/ComponentCamera.cpp
  Source/src/components/ComponentDirLight.cpp
  Source/src/components/ComponentMesh.cpp
  Source/src/components/ComponentPointLight.cpp
  Source/src/components/ComponentSpotLight.cpp
  Source/src/components/ComponentTransform.cpp
  Source/src/components/ComponentTransform.h
  Source/src/core/GameObject.cpp
  Source/src/core/GameObject.h
  Source/src/core/Scene.cpp
  Source/src/modules/ModuleCamera.cpp
  Source/src/ui/WindowScene.cpp
Labels: enhancement

#16 Added Tooltips to Icon Buttons
  Source/src/ui/ImGuiUtils.h
  Source/src/ui/ImguiUtils.cpp
  Source/src/ui/WindowScene.cpp
  Source/src/ui/WindowScene.h
Labels: enhancement

#17 Game object selection outside of scene window
  Source/src/ui/WindowScene.cpp
Labels: bugfix

#18 Port vicenc edward material editor - part 1
  Source/src/components/ComponentMaterial.cpp
  Source/src/resources/ResourceMaterial.h
Labels: enhancement

#20 Fixing PCH configuration
  Source/Engine.vcxproj
Labels: bugfix

#19 Resizing on gizmos rotates the object
  Source/src/ui/ImGuiUtils.h
  Source/src/ui/ImguiUtils.cpp
  Source/src/ui/WindowScene.cpp
Labels: enhancement, bugfix

#26 Now the compiler only shows warnings for the codes we wrote in our project.
  Source/Engine.vcxproj
  Source/src/Globals.h
  Source/src/Quadtree.cpp
  Source/src/Quadtree.h
  Source/src/RenderList.h
  Source/src/components/ComponentCamera.h
  Source/src/components/ComponentMaterial.h
  Source/src/components/ComponentMesh.h
  Source/src/core/GameObject.h
  Source/src/core/Scene.cpp
  Source/src/core/Scene.h
  Source/src/core/serialization/TypeConverter.h
  Source/src/importers/MaterialImporter.h
  Source/src/importers/MeshImporter.h
  Source/src/modules/ModuleHardware.h
  Source/src/modules/ModuleInput.h
  Source/src/modules/ModuleTexture.h
  Source/src/modules/ModuleWindow.h
  Source/src/resources/ResourceMesh.h
  Source/src/ui/ImGuiUtils.h
  Source/src/ui/ImguiUtils.cpp
  Source/src/utils/JsonFormatterValue.h
  Source/vendors/ImGuiFileDialog-0.6.3/ImGuiFileDialog.cpp
Labels: enhancement
